// <auto-generated />
using System;
using DnDTeamGame.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DnDTeamGame.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231023151050_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AbilityEntityCharacterEntity", b =>
                {
                    b.Property<int>("AbilitiesListAbilityId")
                        .HasColumnType("int");

                    b.Property<int>("CharacterListCharacterId")
                        .HasColumnType("int");

                    b.HasKey("AbilitiesListAbilityId", "CharacterListCharacterId");

                    b.HasIndex("CharacterListCharacterId");

                    b.ToTable("AbilityEntityCharacterEntity");
                });

            modelBuilder.Entity("ArmourEntityCharacterEntity", b =>
                {
                    b.Property<int>("ArmoursListArmourId")
                        .HasColumnType("int");

                    b.Property<int>("CharacterListCharacterId")
                        .HasColumnType("int");

                    b.HasKey("ArmoursListArmourId", "CharacterListCharacterId");

                    b.HasIndex("CharacterListCharacterId");

                    b.ToTable("ArmourEntityCharacterEntity");
                });

            modelBuilder.Entity("CharacterEntityConsumableEntity", b =>
                {
                    b.Property<int>("CharacterListCharacterId")
                        .HasColumnType("int");

                    b.Property<int>("ConsumablesListConsumableId")
                        .HasColumnType("int");

                    b.HasKey("CharacterListCharacterId", "ConsumablesListConsumableId");

                    b.HasIndex("ConsumablesListConsumableId");

                    b.ToTable("CharacterEntityConsumableEntity");
                });

            modelBuilder.Entity("CharacterEntityVehicleEntity", b =>
                {
                    b.Property<int>("CharacterListCharacterId")
                        .HasColumnType("int");

                    b.Property<int>("VehiclesListVehicleId")
                        .HasColumnType("int");

                    b.HasKey("CharacterListCharacterId", "VehiclesListVehicleId");

                    b.HasIndex("VehiclesListVehicleId");

                    b.ToTable("CharacterEntityVehicleEntity");
                });

            modelBuilder.Entity("CharacterEntityWeaponEntity", b =>
                {
                    b.Property<int>("CharacterListCharacterId")
                        .HasColumnType("int");

                    b.Property<int>("WeaponsListWeaponId")
                        .HasColumnType("int");

                    b.HasKey("CharacterListCharacterId", "WeaponsListWeaponId");

                    b.HasIndex("WeaponsListWeaponId");

                    b.ToTable("CharacterEntityWeaponEntity");
                });

            modelBuilder.Entity("DnDTeamGame.Data.Entities.AbilityEntity", b =>
                {
                    b.Property<int>("AbilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AbilityId"));

                    b.Property<int>("AbilityAttackDamage")
                        .HasColumnType("int");

                    b.Property<bool>("AbilityDamageMultipleEnemy")
                        .HasColumnType("bit");

                    b.Property<bool>("AbilityDamageSingleEnemy")
                        .HasColumnType("bit");

                    b.Property<int>("AbilityDefenseIncrease")
                        .HasColumnType("int");

                    b.Property<string>("AbilityDescription")
                        .IsRequired()
                        .HasMaxLength(7500)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AbilityEffectAttack")
                        .HasColumnType("bit");

                    b.Property<bool>("AbilityEffectDefenseEnhancement")
                        .HasColumnType("bit");

                    b.Property<bool>("AbilityEffectHealthEnhancement")
                        .HasColumnType("bit");

                    b.Property<string>("AbilityEffectTimeLimit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AbilityEffectType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AbilityHasStatusEffect")
                        .HasColumnType("bit");

                    b.Property<int>("AbilityHealingAmount")
                        .HasColumnType("int");

                    b.Property<string>("AbilityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AbilityId");

                    b.ToTable("Abilities");

                    b.HasData(
                        new
                        {
                            AbilityId = 1,
                            AbilityAttackDamage = 0,
                            AbilityDamageMultipleEnemy = false,
                            AbilityDamageSingleEnemy = false,
                            AbilityDefenseIncrease = 0,
                            AbilityDescription = "Invisibility, considered to be the supreme form of camouflage, as it does not reveal to the viewer any kind of vital signs, visual effects, or any frequencies of the electromagnetic spectrum detectable to the human eye, instead making use of radio, infrared or ultraviolet wavelengths.",
                            AbilityEffectAttack = false,
                            AbilityEffectDefenseEnhancement = false,
                            AbilityEffectHealthEnhancement = false,
                            AbilityEffectTimeLimit = "30 Seconds",
                            AbilityEffectType = "Physical Status Effect",
                            AbilityHasStatusEffect = true,
                            AbilityHealingAmount = 0,
                            AbilityName = "Invisibility"
                        },
                        new
                        {
                            AbilityId = 2,
                            AbilityAttackDamage = 0,
                            AbilityDamageMultipleEnemy = false,
                            AbilityDamageSingleEnemy = false,
                            AbilityDefenseIncrease = 0,
                            AbilityDescription = "Restores a portion of your health.",
                            AbilityEffectAttack = false,
                            AbilityEffectDefenseEnhancement = false,
                            AbilityEffectHealthEnhancement = true,
                            AbilityEffectTimeLimit = "",
                            AbilityEffectType = "Healing Ability",
                            AbilityHasStatusEffect = false,
                            AbilityHealingAmount = 20,
                            AbilityName = "Rejuvenation"
                        },
                        new
                        {
                            AbilityId = 3,
                            AbilityAttackDamage = 35,
                            AbilityDamageMultipleEnemy = false,
                            AbilityDamageSingleEnemy = false,
                            AbilityDefenseIncrease = 0,
                            AbilityDescription = "A seven-hit skill that consists of various slashes, several full circle spins and a backwards somersault.",
                            AbilityEffectAttack = true,
                            AbilityEffectDefenseEnhancement = false,
                            AbilityEffectHealthEnhancement = false,
                            AbilityEffectTimeLimit = "",
                            AbilityEffectType = "Sword Attack Ability",
                            AbilityHasStatusEffect = false,
                            AbilityHealingAmount = 0,
                            AbilityName = "Deadly Sins"
                        },
                        new
                        {
                            AbilityId = 4,
                            AbilityAttackDamage = 0,
                            AbilityDamageMultipleEnemy = false,
                            AbilityDamageSingleEnemy = false,
                            AbilityDefenseIncrease = 100,
                            AbilityDescription = "A defence skill that increases the player's Defence for a single second to such an extent that their entire body becomes harder than a set of full plate armour. Activation requires the player to be unarmed and only wearing non-metallic armour.",
                            AbilityEffectAttack = false,
                            AbilityEffectDefenseEnhancement = true,
                            AbilityEffectHealthEnhancement = false,
                            AbilityEffectTimeLimit = "",
                            AbilityEffectType = "Defensive Ability",
                            AbilityHasStatusEffect = false,
                            AbilityHealingAmount = 0,
                            AbilityName = "Haganeri"
                        });
                });

            modelBuilder.Entity("DnDTeamGame.Data.Entities.ArmourEntity", b =>
                {
                    b.Property<int>("ArmourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArmourId"));

                    b.Property<string>("ArmourDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("ArmourIncreasesHealth")
                        .HasColumnType("bit");

                    b.Property<bool>("ArmourIncreasesRangedAttacks")
                        .HasColumnType("bit");

                    b.Property<bool>("ArmourIncreasesSwordAttacks")
                        .HasColumnType("bit");

                    b.Property<string>("ArmourName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ArmourProvidesDefense")
                        .HasColumnType("bit");

                    b.Property<int>("IncreasedDefenseAmount")
                        .HasColumnType("int");

                    b.Property<int>("IncreasedHealthAmount")
                        .HasColumnType("int");

                    b.Property<int>("IncreasedRangeAttackDamageAmount")
                        .HasColumnType("int");

                    b.Property<int>("IncreasedSwordDamageAmount")
                        .HasColumnType("int");

                    b.HasKey("ArmourId");

                    b.ToTable("Armours");

                    b.HasData(
                        new
                        {
                            ArmourId = 1,
                            ArmourDescription = "A suit of armor made from the scales of a dragon, offering excellent protection against fire and other elemental attacks.",
                            ArmourIncreasesHealth = true,
                            ArmourIncreasesRangedAttacks = false,
                            ArmourIncreasesSwordAttacks = false,
                            ArmourName = "Dragon Scale Mail",
                            ArmourProvidesDefense = true,
                            IncreasedDefenseAmount = 15,
                            IncreasedHealthAmount = 5,
                            IncreasedRangeAttackDamageAmount = 0,
                            IncreasedSwordDamageAmount = 0
                        },
                        new
                        {
                            ArmourId = 2,
                            ArmourDescription = "Lightweight and finely crafted armor of the elves, known for its flexibility and grace.",
                            ArmourIncreasesHealth = false,
                            ArmourIncreasesRangedAttacks = true,
                            ArmourIncreasesSwordAttacks = true,
                            ArmourName = "Elven Chainmail",
                            ArmourProvidesDefense = false,
                            IncreasedDefenseAmount = 0,
                            IncreasedHealthAmount = 0,
                            IncreasedRangeAttackDamageAmount = 10,
                            IncreasedSwordDamageAmount = 5
                        },
                        new
                        {
                            ArmourId = 3,
                            ArmourDescription = "An ornate and majestic suit of armor that grants the wearer resistance to fire damage and the ability to rise from the ashes once per day.",
                            ArmourIncreasesHealth = true,
                            ArmourIncreasesRangedAttacks = false,
                            ArmourIncreasesSwordAttacks = false,
                            ArmourName = "Plate Armor of the Phoenix",
                            ArmourProvidesDefense = true,
                            IncreasedDefenseAmount = 35,
                            IncreasedHealthAmount = 100,
                            IncreasedRangeAttackDamageAmount = 0,
                            IncreasedSwordDamageAmount = 0
                        },
                        new
                        {
                            ArmourId = 4,
                            ArmourDescription = "A dark and stealthy cloak that shrouds the wearer in shadows, making them harder to detect.",
                            ArmourIncreasesHealth = false,
                            ArmourIncreasesRangedAttacks = false,
                            ArmourIncreasesSwordAttacks = false,
                            ArmourName = "Shadow Cloak",
                            ArmourProvidesDefense = true,
                            IncreasedDefenseAmount = 35,
                            IncreasedHealthAmount = 0,
                            IncreasedRangeAttackDamageAmount = 0,
                            IncreasedSwordDamageAmount = 0
                        },
                        new
                        {
                            ArmourId = 5,
                            ArmourDescription = "A set of dark and silent attire, designed for stealthy assassins, allowing them to move undetected.",
                            ArmourIncreasesHealth = false,
                            ArmourIncreasesRangedAttacks = true,
                            ArmourIncreasesSwordAttacks = false,
                            ArmourName = "Assassin's Shadow Garb",
                            ArmourProvidesDefense = true,
                            IncreasedDefenseAmount = 55,
                            IncreasedHealthAmount = 0,
                            IncreasedRangeAttackDamageAmount = 25,
                            IncreasedSwordDamageAmount = 0
                        },
                        new
                        {
                            ArmourId = 6,
                            ArmourDescription = "The regal attire of a powerful archmage, granting immense magical prowess and defenses.",
                            ArmourIncreasesHealth = false,
                            ArmourIncreasesRangedAttacks = true,
                            ArmourIncreasesSwordAttacks = true,
                            ArmourName = "Archmage's Regalia",
                            ArmourProvidesDefense = false,
                            IncreasedDefenseAmount = 0,
                            IncreasedHealthAmount = 0,
                            IncreasedRangeAttackDamageAmount = 25,
                            IncreasedSwordDamageAmount = 25
                        },
                        new
                        {
                            ArmourId = 7,
                            ArmourDescription = "Enigmatic robes that empower warlocks with eldritch magic and otherworldly abilities.",
                            ArmourIncreasesHealth = false,
                            ArmourIncreasesRangedAttacks = true,
                            ArmourIncreasesSwordAttacks = false,
                            ArmourName = "Warlock's Eldritch Vestments",
                            ArmourProvidesDefense = true,
                            IncreasedDefenseAmount = 35,
                            IncreasedHealthAmount = 0,
                            IncreasedRangeAttackDamageAmount = 25,
                            IncreasedSwordDamageAmount = 0
                        },
                        new
                        {
                            ArmourId = 8,
                            ArmourDescription = "A lightweight, silvery chainmail made from mithril, providing excellent protection without hindering mobility.",
                            ArmourIncreasesHealth = false,
                            ArmourIncreasesRangedAttacks = false,
                            ArmourIncreasesSwordAttacks = false,
                            ArmourName = "Mithril Chain",
                            ArmourProvidesDefense = true,
                            IncreasedDefenseAmount = 40,
                            IncreasedHealthAmount = 0,
                            IncreasedRangeAttackDamageAmount = 0,
                            IncreasedSwordDamageAmount = 0
                        },
                        new
                        {
                            ArmourId = 9,
                            ArmourDescription = "Crafted from the hide of a kraken, this armor provides resistance to aquatic threats and great flexibility.",
                            ArmourIncreasesHealth = false,
                            ArmourIncreasesRangedAttacks = false,
                            ArmourIncreasesSwordAttacks = true,
                            ArmourName = "Kraken Hide Armor",
                            ArmourProvidesDefense = true,
                            IncreasedDefenseAmount = 25,
                            IncreasedHealthAmount = 0,
                            IncreasedRangeAttackDamageAmount = 0,
                            IncreasedSwordDamageAmount = 15
                        },
                        new
                        {
                            ArmourId = 10,
                            ArmourDescription = "A sleek and agile leather vest favored by rogues and thieves, providing ease of movement and subtlety.",
                            ArmourIncreasesHealth = true,
                            ArmourIncreasesRangedAttacks = true,
                            ArmourIncreasesSwordAttacks = false,
                            ArmourName = "Leather Vest of the Rogue",
                            ArmourProvidesDefense = true,
                            IncreasedDefenseAmount = 15,
                            IncreasedHealthAmount = 15,
                            IncreasedRangeAttackDamageAmount = 35,
                            IncreasedSwordDamageAmount = 0
                        },
                        new
                        {
                            ArmourId = 11,
                            ArmourDescription = "Massive and imposing armor fit for a giant, offering incredible strength and resilience.",
                            ArmourIncreasesHealth = true,
                            ArmourIncreasesRangedAttacks = false,
                            ArmourIncreasesSwordAttacks = true,
                            ArmourName = "Titan's Plate",
                            ArmourProvidesDefense = true,
                            IncreasedDefenseAmount = 40,
                            IncreasedHealthAmount = 15,
                            IncreasedRangeAttackDamageAmount = 0,
                            IncreasedSwordDamageAmount = 40
                        });
                });

            modelBuilder.Entity("DnDTeamGame.Data.Entities.BodyTypeEntity", b =>
                {
                    b.Property<int>("BodyTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BodyTypeId"));

                    b.Property<string>("BodyTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BodyTypeId");

                    b.ToTable("BodyTypes");

                    b.HasData(
                        new
                        {
                            BodyTypeId = 1,
                            BodyTypeName = "Muscular"
                        },
                        new
                        {
                            BodyTypeId = 2,
                            BodyTypeName = "Atheletic"
                        },
                        new
                        {
                            BodyTypeId = 3,
                            BodyTypeName = "SlimSkinny"
                        },
                        new
                        {
                            BodyTypeId = 4,
                            BodyTypeName = "Giant"
                        },
                        new
                        {
                            BodyTypeId = 5,
                            BodyTypeName = "BigBoned"
                        },
                        new
                        {
                            BodyTypeId = 6,
                            BodyTypeName = "SlimMuscular"
                        });
                });

            modelBuilder.Entity("DnDTeamGame.Data.Entities.CharacterClassEntity", b =>
                {
                    b.Property<int>("CharacterClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterClassId"));

                    b.Property<string>("CharacterClassDescription")
                        .IsRequired()
                        .HasMaxLength(750)
                        .HasColumnType("nvarchar(750)");

                    b.Property<string>("CharacterClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CharacterClassSpecialAbility")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassBackstoryForCharacter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpeacialAbilityDefenseAmount")
                        .HasColumnType("int");

                    b.Property<int>("SpecialAbilityDamage")
                        .HasColumnType("int");

                    b.Property<string>("SpecialAbilityDescription")
                        .IsRequired()
                        .HasMaxLength(750)
                        .HasColumnType("nvarchar(750)");

                    b.Property<string>("SpecialAbilityDuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecialAbilityHealingAmount")
                        .HasColumnType("int");

                    b.Property<bool>("SpecialAbilityHeals")
                        .HasColumnType("bit");

                    b.Property<bool>("SpecialAbilityIsAnAttack")
                        .HasColumnType("bit");

                    b.Property<bool>("SpecialAbilityProvidesDefense")
                        .HasColumnType("bit");

                    b.Property<bool>("SpecialAbilityProvidesStatusEffect")
                        .HasColumnType("bit");

                    b.HasKey("CharacterClassId");

                    b.ToTable("CharacterClasses");

                    b.HasData(
                        new
                        {
                            CharacterClassId = 1,
                            CharacterClassDescription = "Warriors equip themselves carefully for combat and engage their enemies head-on, letting attacks glance off their heavy armor. They use diverse combat tactics and a wide variety of weapon types to protect their more vulnerable allies. Warriors must carefully master their rage – the power behind their strongest attacks – in order to maximize their effectiveness in combat.",
                            CharacterClassName = "Warrior",
                            CharacterClassSpecialAbility = "Rage",
                            ClassBackstoryForCharacter = "You hail from a long line of noble knights sworn to protect the kingdom. Trained in the art of combat \nfrom a young age, you became a renowned warrior and commander of the royal army. Beneath your stoic \nexterior lies a burning desire to uncover the truth about a dark prophecy that foretells the return of \nan ancient evil. As the kingdom teeters on the brink of chaos, you decide to take up the sword, determined \nto fulfill the family's oath and vanquish the looming threat.",
                            SpeacialAbilityDefenseAmount = 0,
                            SpecialAbilityDamage = 55,
                            SpecialAbilityDescription = "As warriors deal or take damage, their rage grows, allowing them to deliver truly crushing attacks in the heat of battle.",
                            SpecialAbilityDuration = "25 seconds",
                            SpecialAbilityHealingAmount = 0,
                            SpecialAbilityHeals = false,
                            SpecialAbilityIsAnAttack = true,
                            SpecialAbilityProvidesDefense = false,
                            SpecialAbilityProvidesStatusEffect = false
                        },
                        new
                        {
                            CharacterClassId = 2,
                            CharacterClassDescription = "Hunters battle their foes at a distance or up close, commanding their pets to attack while they nock their arrows, fire their guns, or ready their polearms. Though their weapons are effective at short and long ranges, hunters are also highly mobile. They can evade or restrain their foes to control the arena of battle",
                            CharacterClassName = "Hunter",
                            CharacterClassSpecialAbility = "Tamer of the Wilds",
                            ClassBackstoryForCharacter = " You have become a skilled hunter, hailing from the Elven Woodlands. The connection you have with the natural world and mastery of archery have made you\na renowned protector of the forest. You joins the other heroes, using your keen senses to detect the malevolent forces\nthreatening the realm. This is not only a quest to safeguard the homeland but also to restore the balance of nature.",
                            SpeacialAbilityDefenseAmount = 0,
                            SpecialAbilityDamage = 25,
                            SpecialAbilityDescription = "Hunters tame the beasts of the wild, and those beasts serve in return by assaulting their enemies and shielding them from harm.",
                            SpecialAbilityDuration = "45 seconds",
                            SpecialAbilityHealingAmount = 0,
                            SpecialAbilityHeals = false,
                            SpecialAbilityIsAnAttack = true,
                            SpecialAbilityProvidesDefense = false,
                            SpecialAbilityProvidesStatusEffect = false
                        },
                        new
                        {
                            CharacterClassId = 3,
                            CharacterClassDescription = "Rogues often initiate combat with a surprise attack from the shadows, leading with vicious melee strikes. When in protracted battles, they utilize a successive combination of carefully chosen attacks to soften the enemy up for a killing blow. Rogues must take special care when selecting targets so that their combo attacks are not wasted, and they must be conscious of when to hide or flee if a battle turns against them.",
                            CharacterClassName = "Rogue",
                            CharacterClassSpecialAbility = "Stealth Attack",
                            ClassBackstoryForCharacter = " You grew up an orphan on the unforgiving streets of the shadowy city of Rogarth. Your life of \npetty theft and cunning escapes changed when you discovered a cryptic map, hinting at the existence of an\nartifact that could shift the balance of power in the kingdom. Your past as a rogue makes you an invaluable  \nasset in infiltrating dangerous territories, and you are driven to find the artifact and secure the future.",
                            SpeacialAbilityDefenseAmount = 0,
                            SpecialAbilityDamage = 30,
                            SpecialAbilityDescription = "Rogues sneak about the battlefield, hiding from enemies and delivering surprise attacks to the unwary when opportunity arises.",
                            SpecialAbilityDuration = "20 seconds",
                            SpecialAbilityHealingAmount = 0,
                            SpecialAbilityHeals = false,
                            SpecialAbilityIsAnAttack = true,
                            SpecialAbilityProvidesDefense = false,
                            SpecialAbilityProvidesStatusEffect = true
                        },
                        new
                        {
                            CharacterClassId = 4,
                            CharacterClassDescription = "Mages demolish their foes with arcane incantations. Although they wield powerful offensive spells, mages are fragile and lightly armored, making them particularly vulnerable to close-range attacks. Wise mages make careful use of their spells to keep their foes at a distance or hold them in place.",
                            CharacterClassName = "Mage",
                            CharacterClassSpecialAbility = "Elemental Nova Blast",
                            ClassBackstoryForCharacter = " You have becoma a gifted mage, spending your youth studying the arcane arts in the Tower of Mysteries. \nYou now possess a unique ability to see glimpses of the future through magic. The visions reveal an imminent \ncataclysm that threatens to plunge the world into darkness. To avert this fate, you must harness your powers \nand unite with other heroes to unlock the secrets hidden within ancient artifacts, preventing the oncoming disaster.",
                            SpeacialAbilityDefenseAmount = 0,
                            SpecialAbilityDamage = 40,
                            SpecialAbilityDescription = "By calling upon sheets of ice, columns of flame, and waves of arcane power, mages can effectively attack multiple foes at the same time.",
                            SpecialAbilityDuration = "",
                            SpecialAbilityHealingAmount = 0,
                            SpecialAbilityHeals = false,
                            SpecialAbilityIsAnAttack = true,
                            SpecialAbilityProvidesDefense = false,
                            SpecialAbilityProvidesStatusEffect = false
                        },
                        new
                        {
                            CharacterClassId = 5,
                            CharacterClassDescription = "Death Knights engage their foes up-close, supplementing swings of their weapons with dark magic that renders enemies vulnerable or damages them with unholy power. They drag foes into one-on-one conflicts, compelling them to focus their attacks away from weaker companions. To prevent their enemies from fleeing their grasp, death knights must remain mindful of the power they call forth from runes, and pace their attacks appropriately.",
                            CharacterClassName = "Death Knight",
                            CharacterClassSpecialAbility = "RuneForged Starburst Stream",
                            ClassBackstoryForCharacter = "You were once a valiant knight, but corruption took hold when you were raised from the dead as a death knight by a malevolent necromancer.\ntormented by your past deeds, you now seek redemption. Using your unholy powers are harnessing them for a noble cause:\nto vanquish the darkness you once served. Your presence serves as a constant reminder of the thin line between light and shadow.",
                            SpeacialAbilityDefenseAmount = 0,
                            SpecialAbilityDamage = 45,
                            SpecialAbilityDescription = "Death knight runeblades are empowered with dark magic; they can expend the power of their runes for vicious attacks.",
                            SpecialAbilityDuration = "",
                            SpecialAbilityHealingAmount = 0,
                            SpecialAbilityHeals = false,
                            SpecialAbilityIsAnAttack = true,
                            SpecialAbilityProvidesDefense = false,
                            SpecialAbilityProvidesStatusEffect = false
                        },
                        new
                        {
                            CharacterClassId = 6,
                            CharacterClassDescription = "Paladins stand directly in front of their enemies, relying on heavy armor and healing in order to survive incoming attacks. Whether with massive shields or crushing two-handed weapons, Paladins are able to keep claws and swords from their weaker fellows or they use healing magic to ensure that they remain on their feet.",
                            CharacterClassName = "Paladin",
                            CharacterClassSpecialAbility = "Healing Nova Blessing",
                            ClassBackstoryForCharacter = "A Dawnbringer, a devoted paladin of a divine order, you set out on a quest with a sacred purpose.\nYour unwavering faith is guided by visions of an ancient prophecy, which you believes holds the key to thwarting the ancient evil.\nArmed with holy magic and a deep sense of duty, You represent the light's beacon in the darkest of times.",
                            SpeacialAbilityDefenseAmount = 0,
                            SpecialAbilityDamage = 0,
                            SpecialAbilityDescription = "Paladins potent healing abilities can ensure that they and their allies remain in fighting shape.",
                            SpecialAbilityDuration = "",
                            SpecialAbilityHealingAmount = 25,
                            SpecialAbilityHeals = true,
                            SpecialAbilityIsAnAttack = false,
                            SpecialAbilityProvidesDefense = false,
                            SpecialAbilityProvidesStatusEffect = false
                        },
                        new
                        {
                            CharacterClassId = 7,
                            CharacterClassDescription = "Masters of mechanical mayhem, engineers love to tinker with explosives, elixirs, and all manner of hazardous gadgets. They support their allies with alchemic weaponry, deploy ingenious inventions, or lay waste to foes with a wide array of mines, bombs, and grenades.",
                            CharacterClassName = "Engineer",
                            CharacterClassSpecialAbility = "Rapid Turret Deployment",
                            ClassBackstoryForCharacter = " You have become a brilliant engineer, dedicating your life to inventing ingenious contraptions. The mysterious artifacts \ndiscovered in the ruins of the acients reveal their dark secrets to you. As an inventor, your knowledge \nof machinery and gadgets makes you a vital ally in deciphering the ancient devices that hold the power to avert the impending catastrophe.",
                            SpeacialAbilityDefenseAmount = 0,
                            SpecialAbilityDamage = 30,
                            SpecialAbilityDescription = "An engineer constructs turrets to help defend and control an area. These devices can pound the ground to damage enemies, disperse healing mist to aid allies, fire off rockets, and more.",
                            SpecialAbilityDuration = "20 seconds",
                            SpecialAbilityHealingAmount = 0,
                            SpecialAbilityHeals = false,
                            SpecialAbilityIsAnAttack = true,
                            SpecialAbilityProvidesDefense = false,
                            SpecialAbilityProvidesStatusEffect = false
                        },
                        new
                        {
                            CharacterClassId = 8,
                            CharacterClassDescription = "Practitioners of the dark arts, necromancers summon minions, wield the power of ritual, and heal themselves with blood magic. Necromancers feed on life force, which they can leverage offensively or use to delay their own demise.",
                            CharacterClassName = "Necromancer",
                            CharacterClassSpecialAbility = "Life Force Drain",
                            ClassBackstoryForCharacter = "You have been an outcast, shunned for the mastery over the dark arts of necromancy. Your affinity for \ncommunicating with the spirits of the deceased led you to uncover an ancient curse that has bound restless souls\nto the world. Your quest is to break the curse, not only to gain acceptance among the living but also to liberate the \n tormented spirits. In the course of the journey, you cross paths with other heroes, forming an unlikely alliance to combat the common threat.",
                            SpeacialAbilityDefenseAmount = 0,
                            SpecialAbilityDamage = 15,
                            SpecialAbilityDescription = "Life force is a special type of energy that necromancers draw from their enemies. Once theyve collected enough life force, necromancers can activate their Death Shroud, entering a spirit form. Life force can be gathered from certain weapon attacks and especially from deaths that happen near the necromancer.",
                            SpecialAbilityDuration = "20 seconds",
                            SpecialAbilityHealingAmount = 30,
                            SpecialAbilityHeals = true,
                            SpecialAbilityIsAnAttack = true,
                            SpecialAbilityProvidesDefense = false,
                            SpecialAbilityProvidesStatusEffect = false
                        });
                });

            modelBuilder.Entity("DnDTeamGame.Data.Entities.CharacterEntity", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterId"));

                    b.Property<int>("BodyTypeId")
                        .HasColumnType("int");

                    b.Property<double>("CharacterBaseAttackDamage")
                        .HasColumnType("float");

                    b.Property<int>("CharacterBaseDefense")
                        .HasColumnType("int");

                    b.Property<int>("CharacterClassId")
                        .HasColumnType("int");

                    b.Property<string>("CharacterDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CharacterHealth")
                        .HasColumnType("int");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("HairColorId")
                        .HasColumnType("int");

                    b.Property<int>("HairStyleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CharacterId");

                    b.HasIndex("BodyTypeId");

                    b.HasIndex("CharacterClassId");

                    b.HasIndex("HairColorId");

                    b.HasIndex("HairStyleId");

                    b.HasIndex("UserId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("DnDTeamGame.Data.Entities.ConsumableEntity", b =>
                {
                    b.Property<int>("ConsumableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsumableId"));

                    b.Property<int?>("ConsumableAttackIncreaseAmount")
                        .HasColumnType("int");

                    b.Property<string>("ConsumableDamageToEnemy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ConsumableDefenseIncreaseAmount")
                        .HasColumnType("int");

                    b.Property<string>("ConsumableDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("ConsumableDoesDamageToEnemy")
                        .HasColumnType("bit");

                    b.Property<string>("ConsumableEffect")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("ConsumableHealthIncreaseAmount")
                        .HasColumnType("int");

                    b.Property<bool>("ConsumableIncreaseAttack")
                        .HasColumnType("bit");

                    b.Property<bool>("ConsumableIncreaseDefense")
                        .HasColumnType("bit");

                    b.Property<bool>("ConsumableIncreaseHealth")
                        .HasColumnType("bit");

                    b.Property<string>("ConsumableName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ConsumableId");

                    b.ToTable("Consumables");

                    b.HasData(
                        new
                        {
                            ConsumableId = 1,
                            ConsumableAttackIncreaseAmount = 0,
                            ConsumableDamageToEnemy = "",
                            ConsumableDefenseIncreaseAmount = 0,
                            ConsumableDescription = "A magical potion that restores a portion of your health.",
                            ConsumableDoesDamageToEnemy = false,
                            ConsumableEffect = "Restores 50 health points.",
                            ConsumableHealthIncreaseAmount = 50,
                            ConsumableIncreaseAttack = false,
                            ConsumableIncreaseDefense = false,
                            ConsumableIncreaseHealth = true,
                            ConsumableName = "Health Potion"
                        },
                        new
                        {
                            ConsumableId = 2,
                            ConsumableAttackIncreaseAmount = 0,
                            ConsumableDamageToEnemy = "",
                            ConsumableDefenseIncreaseAmount = 20,
                            ConsumableDescription = "A potent elixir that temporarily enhances your defensive capabilities.",
                            ConsumableDoesDamageToEnemy = false,
                            ConsumableEffect = "Increases your defense by 20% for 3 minutes.",
                            ConsumableHealthIncreaseAmount = 0,
                            ConsumableIncreaseAttack = false,
                            ConsumableIncreaseDefense = true,
                            ConsumableIncreaseHealth = false,
                            ConsumableName = "Elixir of Protection"
                        },
                        new
                        {
                            ConsumableId = 3,
                            ConsumableAttackIncreaseAmount = 30,
                            ConsumableDamageToEnemy = "",
                            ConsumableDefenseIncreaseAmount = 15,
                            ConsumableDescription = "A strong potion that grants you temporary, furious strength in battle.",
                            ConsumableDoesDamageToEnemy = false,
                            ConsumableEffect = "Increases your attack damage by 30% for 2 minutes but decreases defense by 15%.",
                            ConsumableHealthIncreaseAmount = 0,
                            ConsumableIncreaseAttack = true,
                            ConsumableIncreaseDefense = true,
                            ConsumableIncreaseHealth = false,
                            ConsumableName = "Berserker's Brew"
                        },
                        new
                        {
                            ConsumableId = 4,
                            ConsumableAttackIncreaseAmount = 30,
                            ConsumableDamageToEnemy = "Paralyze Enemy for 15 Seconds",
                            ConsumableDefenseIncreaseAmount = 0,
                            ConsumableDescription = "A mystical stone with the petrifying power of the Gorgon.",
                            ConsumableDoesDamageToEnemy = true,
                            ConsumableEffect = "Can be used to temporarily paralyze or petrify enemies.",
                            ConsumableHealthIncreaseAmount = 0,
                            ConsumableIncreaseAttack = false,
                            ConsumableIncreaseDefense = false,
                            ConsumableIncreaseHealth = false,
                            ConsumableName = "Gorgon's Gaze Stone"
                        },
                        new
                        {
                            ConsumableId = 5,
                            ConsumableAttackIncreaseAmount = 0,
                            ConsumableDamageToEnemy = "Paralyze Enemy for 15 Seconds",
                            ConsumableDefenseIncreaseAmount = 50,
                            ConsumableDescription = " A luminous elixir that temporarily creates a protective energy shield.",
                            ConsumableDoesDamageToEnemy = false,
                            ConsumableEffect = "Grants a temporary energy shield that reflects incoming projectiles.",
                            ConsumableHealthIncreaseAmount = 0,
                            ConsumableIncreaseAttack = false,
                            ConsumableIncreaseDefense = true,
                            ConsumableIncreaseHealth = false,
                            ConsumableName = "Mirror Shield Elixir"
                        },
                        new
                        {
                            ConsumableId = 6,
                            ConsumableAttackIncreaseAmount = 0,
                            ConsumableDamageToEnemy = "",
                            ConsumableDefenseIncreaseAmount = 0,
                            ConsumableDescription = "An ancient scroll with the power to instantly teleport the user to a previously visited location.",
                            ConsumableDoesDamageToEnemy = false,
                            ConsumableEffect = "Teleports you to a known location on the map.",
                            ConsumableHealthIncreaseAmount = 0,
                            ConsumableIncreaseAttack = false,
                            ConsumableIncreaseDefense = false,
                            ConsumableIncreaseHealth = false,
                            ConsumableName = "Scroll of Teleportation"
                        },
                        new
                        {
                            ConsumableId = 7,
                            ConsumableAttackIncreaseAmount = 0,
                            ConsumableDamageToEnemy = "",
                            ConsumableDefenseIncreaseAmount = 100,
                            ConsumableDescription = "A rare and delicious fruit said to grant immortality in mythology.",
                            ConsumableDoesDamageToEnemy = false,
                            ConsumableEffect = "Fully restores health and grants temporary invincibility.",
                            ConsumableHealthIncreaseAmount = 100,
                            ConsumableIncreaseAttack = false,
                            ConsumableIncreaseDefense = true,
                            ConsumableIncreaseHealth = true,
                            ConsumableName = "Ambrosia Fruit"
                        });
                });

            modelBuilder.Entity("DnDTeamGame.Data.Entities.GameEntity", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"));

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("GameDescription")
                        .IsRequired()
                        .HasMaxLength(7500)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("DnDTeamGame.Data.Entities.HairColorEntity", b =>
                {
                    b.Property<int>("HairColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HairColorId"));

                    b.Property<string>("HairColorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HairColorId");

                    b.ToTable("HairColors");

                    b.HasData(
                        new
                        {
                            HairColorId = 1,
                            HairColorName = "Red"
                        },
                        new
                        {
                            HairColorId = 2,
                            HairColorName = "Blonde"
                        },
                        new
                        {
                            HairColorId = 3,
                            HairColorName = "Silver"
                        },
                        new
                        {
                            HairColorId = 4,
                            HairColorName = "Pink"
                        },
                        new
                        {
                            HairColorId = 5,
                            HairColorName = "Purple"
                        },
                        new
                        {
                            HairColorId = 6,
                            HairColorName = "Orange"
                        },
                        new
                        {
                            HairColorId = 7,
                            HairColorName = "Blue"
                        },
                        new
                        {
                            HairColorId = 8,
                            HairColorName = "Indigo"
                        },
                        new
                        {
                            HairColorId = 9,
                            HairColorName = "Rainbow"
                        },
                        new
                        {
                            HairColorId = 10,
                            HairColorName = "AquaMarine"
                        },
                        new
                        {
                            HairColorId = 11,
                            HairColorName = "Teal"
                        },
                        new
                        {
                            HairColorId = 12,
                            HairColorName = "Green"
                        },
                        new
                        {
                            HairColorId = 13,
                            HairColorName = "Black"
                        },
                        new
                        {
                            HairColorId = 14,
                            HairColorName = "Brown"
                        },
                        new
                        {
                            HairColorId = 15,
                            HairColorName = "White"
                        });
                });

            modelBuilder.Entity("DnDTeamGame.Data.Entities.HairStyleEntity", b =>
                {
                    b.Property<int>("HairStyleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HairStyleId"));

                    b.Property<string>("HairStyleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HairStyleId");

                    b.ToTable("HairStyles");

                    b.HasData(
                        new
                        {
                            HairStyleId = 1,
                            HairStyleName = "Long Hair"
                        },
                        new
                        {
                            HairStyleId = 2,
                            HairStyleName = "Karen's Hair Style"
                        },
                        new
                        {
                            HairStyleId = 3,
                            HairStyleName = "Short Hair"
                        },
                        new
                        {
                            HairStyleId = 4,
                            HairStyleName = "Long Flowing Locks"
                        },
                        new
                        {
                            HairStyleId = 5,
                            HairStyleName = "Braided Warrior's Tresses"
                        },
                        new
                        {
                            HairStyleId = 6,
                            HairStyleName = "Windswept Curls"
                        },
                        new
                        {
                            HairStyleId = 7,
                            HairStyleName = "Elven Pointed Braid"
                        },
                        new
                        {
                            HairStyleId = 8,
                            HairStyleName = "Shaved Sides with Top Knot"
                        },
                        new
                        {
                            HairStyleId = 9,
                            HairStyleName = "Sorceress's Long Braid"
                        },
                        new
                        {
                            HairStyleId = 10,
                            HairStyleName = "Half-Shaved, Half-Long"
                        },
                        new
                        {
                            HairStyleId = 11,
                            HairStyleName = "Pirate's Dreadlocks with Beads"
                        },
                        new
                        {
                            HairStyleId = 12,
                            HairStyleName = "Spiky Anime Style"
                        },
                        new
                        {
                            HairStyleId = 13,
                            HairStyleName = "Bald and Tattooed"
                        },
                        new
                        {
                            HairStyleId = 14,
                            HairStyleName = "Braided Beard with Rings"
                        },
                        new
                        {
                            HairStyleId = 15,
                            HairStyleName = "Mohawk with Tribal Tattoos"
                        });
                });

            modelBuilder.Entity("DnDTeamGame.Data.Entities.MapEntity", b =>
                {
                    b.Property<int>("MapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MapId"));

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDayTime")
                        .HasColumnType("bit");

                    b.Property<string>("MapDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MapName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MapType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PrecipitationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MapId");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("DnDTeamGame.Data.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("DnDTeamGame.Data.Entities.VehicleEntity", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<string>("VehicleAbility")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("VehicleAttackDamage")
                        .HasColumnType("int");

                    b.Property<string>("VehicleDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("VehicleHealth")
                        .HasColumnType("float");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("VehicleSpeed")
                        .HasColumnType("float");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VehicleId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            VehicleAbility = "Charge",
                            VehicleAttackDamage = 10,
                            VehicleDescription = "A powerful warhorse trained for battle, capable of charging into enemy lines.",
                            VehicleHealth = 100.0,
                            VehicleName = "Warhorse",
                            VehicleSpeed = 60.0,
                            VehicleType = "Mount"
                        },
                        new
                        {
                            VehicleId = 2,
                            VehicleAbility = "Aerial Maneuverability",
                            VehicleAttackDamage = 30,
                            VehicleDescription = "A majestic airship that soars through the skies, offering great mobility and firepower.",
                            VehicleHealth = 300.0,
                            VehicleName = "Airship",
                            VehicleSpeed = 120.0,
                            VehicleType = "Flying Vehicle"
                        },
                        new
                        {
                            VehicleId = 3,
                            VehicleAbility = "Heavy Armor",
                            VehicleAttackDamage = 50,
                            VehicleDescription = "A massive mechanical walker armed with heavy artillery, capable of withstanding immense damage.",
                            VehicleHealth = 500.0,
                            VehicleName = "Mechanical Walker",
                            VehicleSpeed = 40.0,
                            VehicleType = "Mechanical"
                        },
                        new
                        {
                            VehicleId = 4,
                            VehicleAbility = "Crunch",
                            VehicleAttackDamage = 75,
                            VehicleDescription = "A massive, fearsome wolf that serves as a mount for those brave enough to tame it. Known for its speed and strength, it's a formidable ally in battle.",
                            VehicleHealth = 250.0,
                            VehicleName = "DireWolf Mount",
                            VehicleSpeed = 35.0,
                            VehicleType = "Mount"
                        },
                        new
                        {
                            VehicleId = 5,
                            VehicleAbility = "Crunch",
                            VehicleAttackDamage = 25,
                            VehicleDescription = " A graceful and magical mount used by the elves, capable of running on water and through dense forests with ease.",
                            VehicleHealth = 250.0,
                            VehicleName = "Elven Leafstrider",
                            VehicleSpeed = 55.0,
                            VehicleType = "Mount"
                        },
                        new
                        {
                            VehicleId = 6,
                            VehicleAbility = "Crunch",
                            VehicleAttackDamage = 25,
                            VehicleDescription = " A majestic creature with the body of a lion and wings of an eagle, perfect for aerial combat and reconnaissance.",
                            VehicleHealth = 200.0,
                            VehicleName = "BuckBeak The Griffon",
                            VehicleSpeed = 65.0,
                            VehicleType = " Flying Mount"
                        });
                });

            modelBuilder.Entity("DnDTeamGame.Data.Entities.WeaponEntity", b =>
                {
                    b.Property<int>("WeaponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeaponId"));

                    b.Property<string>("RangedWeaponDistance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeaponDamageAmount")
                        .HasColumnType("int");

                    b.Property<string>("WeaponDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WeaponGeneratesSplashDamage")
                        .HasColumnType("bit");

                    b.Property<bool>("WeaponIsAMeleeWeapon")
                        .HasColumnType("bit");

                    b.Property<bool>("WeaponIsARangedWeapon")
                        .HasColumnType("bit");

                    b.Property<string>("WeaponName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeaponSplashDamageAmount")
                        .HasColumnType("int");

                    b.Property<string>("WeaponType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WeaponId");

                    b.ToTable("Weapons");

                    b.HasData(
                        new
                        {
                            WeaponId = 1,
                            RangedWeaponDistance = "20 meters",
                            WeaponDamageAmount = 35,
                            WeaponDescription = "A radiant bow blessed by celestial beings, firing arrows of divine light that can smite darkness and heal allies.",
                            WeaponGeneratesSplashDamage = true,
                            WeaponIsAMeleeWeapon = false,
                            WeaponIsARangedWeapon = true,
                            WeaponName = "Celestial Bow of Radiance",
                            WeaponSplashDamageAmount = 10,
                            WeaponType = "Bow and Arrow"
                        },
                        new
                        {
                            WeaponId = 2,
                            RangedWeaponDistance = "",
                            WeaponDamageAmount = 35,
                            WeaponDescription = " A concealed dagger used by rogues for stealthy assassinations, designed to leave no trace behind.",
                            WeaponGeneratesSplashDamage = false,
                            WeaponIsAMeleeWeapon = true,
                            WeaponIsARangedWeapon = false,
                            WeaponName = "Rogue's Dagger of Shadows",
                            WeaponSplashDamageAmount = 0,
                            WeaponType = "Dagger"
                        },
                        new
                        {
                            WeaponId = 3,
                            RangedWeaponDistance = "20 meters",
                            WeaponDamageAmount = 40,
                            WeaponDescription = " A staff that channels the power of dragons, allowing the caster to unleash devastating fire spells.",
                            WeaponGeneratesSplashDamage = true,
                            WeaponIsAMeleeWeapon = false,
                            WeaponIsARangedWeapon = true,
                            WeaponName = "Dragonfire Staff",
                            WeaponSplashDamageAmount = 15,
                            WeaponType = "Mage Staff"
                        },
                        new
                        {
                            WeaponId = 4,
                            RangedWeaponDistance = "",
                            WeaponDamageAmount = 65,
                            WeaponDescription = " A razor-sharp sword that can sever heads with a single swing, a weapon favored by those seeking decapitating strikes.",
                            WeaponGeneratesSplashDamage = false,
                            WeaponIsAMeleeWeapon = true,
                            WeaponIsARangedWeapon = false,
                            WeaponName = "Vorpal Blade",
                            WeaponSplashDamageAmount = 0,
                            WeaponType = "Katana"
                        },
                        new
                        {
                            WeaponId = 5,
                            RangedWeaponDistance = "",
                            WeaponDamageAmount = 45,
                            WeaponDescription = "A massive and sturdy warhammer forged in dwarven forges, able to crush opponents and breach defenses.",
                            WeaponGeneratesSplashDamage = true,
                            WeaponIsAMeleeWeapon = true,
                            WeaponIsARangedWeapon = false,
                            WeaponName = "Dwarven Warhammer",
                            WeaponSplashDamageAmount = 15,
                            WeaponType = "WarHammer"
                        },
                        new
                        {
                            WeaponId = 6,
                            RangedWeaponDistance = "",
                            WeaponDamageAmount = 50,
                            WeaponDescription = "A menacing scythe associated with necromancers, capable of harvesting souls and controlling the undead.",
                            WeaponGeneratesSplashDamage = false,
                            WeaponIsAMeleeWeapon = true,
                            WeaponIsARangedWeapon = false,
                            WeaponName = "Necromancer's Scythe",
                            WeaponSplashDamageAmount = 0,
                            WeaponType = "Scythe"
                        },
                        new
                        {
                            WeaponId = 7,
                            RangedWeaponDistance = "5 meters",
                            WeaponDamageAmount = 30,
                            WeaponDescription = "A cane with concealed tricks and traps, used by jesters and pranksters for both entertainment and subterfuge.",
                            WeaponGeneratesSplashDamage = true,
                            WeaponIsAMeleeWeapon = true,
                            WeaponIsARangedWeapon = true,
                            WeaponName = "Jester's Trickster Cane",
                            WeaponSplashDamageAmount = 15,
                            WeaponType = "Sword"
                        },
                        new
                        {
                            WeaponId = 8,
                            RangedWeaponDistance = "35 meters",
                            WeaponDamageAmount = 45,
                            WeaponDescription = "A cane with concealed tricks and traps, used by jesters and pranksters for both entertainment and subterfuge.",
                            WeaponGeneratesSplashDamage = true,
                            WeaponIsAMeleeWeapon = false,
                            WeaponIsARangedWeapon = true,
                            WeaponName = "Elven Longbow",
                            WeaponSplashDamageAmount = 15,
                            WeaponType = "Bow And Arrow"
                        },
                        new
                        {
                            WeaponId = 9,
                            RangedWeaponDistance = "35 meters",
                            WeaponDamageAmount = 65,
                            WeaponDescription = "The legendary sword of King Arthur, said to be the most powerful and righteous weapon in the realm, capable of vanquishing evil.",
                            WeaponGeneratesSplashDamage = true,
                            WeaponIsAMeleeWeapon = true,
                            WeaponIsARangedWeapon = false,
                            WeaponName = "Excalibur",
                            WeaponSplashDamageAmount = 20,
                            WeaponType = "Sword"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AbilityEntityCharacterEntity", b =>
                {
                    b.HasOne("DnDTeamGame.Data.Entities.AbilityEntity", null)
                        .WithMany()
                        .HasForeignKey("AbilitiesListAbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDTeamGame.Data.Entities.CharacterEntity", null)
                        .WithMany()
                        .HasForeignKey("CharacterListCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArmourEntityCharacterEntity", b =>
                {
                    b.HasOne("DnDTeamGame.Data.Entities.ArmourEntity", null)
                        .WithMany()
                        .HasForeignKey("ArmoursListArmourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDTeamGame.Data.Entities.CharacterEntity", null)
                        .WithMany()
                        .HasForeignKey("CharacterListCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterEntityConsumableEntity", b =>
                {
                    b.HasOne("DnDTeamGame.Data.Entities.CharacterEntity", null)
                        .WithMany()
                        .HasForeignKey("CharacterListCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDTeamGame.Data.Entities.ConsumableEntity", null)
                        .WithMany()
                        .HasForeignKey("ConsumablesListConsumableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterEntityVehicleEntity", b =>
                {
                    b.HasOne("DnDTeamGame.Data.Entities.CharacterEntity", null)
                        .WithMany()
                        .HasForeignKey("CharacterListCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDTeamGame.Data.Entities.VehicleEntity", null)
                        .WithMany()
                        .HasForeignKey("VehiclesListVehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterEntityWeaponEntity", b =>
                {
                    b.HasOne("DnDTeamGame.Data.Entities.CharacterEntity", null)
                        .WithMany()
                        .HasForeignKey("CharacterListCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDTeamGame.Data.Entities.WeaponEntity", null)
                        .WithMany()
                        .HasForeignKey("WeaponsListWeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DnDTeamGame.Data.Entities.CharacterEntity", b =>
                {
                    b.HasOne("DnDTeamGame.Data.Entities.BodyTypeEntity", "BodyType")
                        .WithMany()
                        .HasForeignKey("BodyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDTeamGame.Data.Entities.CharacterClassEntity", "CharacterClass")
                        .WithMany()
                        .HasForeignKey("CharacterClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDTeamGame.Data.Entities.HairColorEntity", "HairColor")
                        .WithMany()
                        .HasForeignKey("HairColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDTeamGame.Data.Entities.HairStyleEntity", "HairStyle")
                        .WithMany()
                        .HasForeignKey("HairStyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDTeamGame.Data.Entities.UserEntity", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BodyType");

                    b.Navigation("CharacterClass");

                    b.Navigation("HairColor");

                    b.Navigation("HairStyle");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DnDTeamGame.Data.Entities.GameEntity", b =>
                {
                    b.HasOne("DnDTeamGame.Data.Entities.UserEntity", "Games")
                        .WithMany("Games")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Games");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("DnDTeamGame.Data.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("DnDTeamGame.Data.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDTeamGame.Data.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("DnDTeamGame.Data.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DnDTeamGame.Data.Entities.UserEntity", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
